# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: toc-gen

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: ./toc-gen
    - name: run toc-gen
      run: java -jar ./toc-gen/target/toc-gen-0.1.jar ${{ secrets.GITHUB_TOKEN }}
    - name: push toc
      uses: EndBug/add-and-commit@v4
      with:
        author_name: lihongjie0209
        author_email: lihongjie0209@gmail.com
        message: "update toc"
        add: "README.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
